
services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: workout_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-workoutdb}  # this means use my .env database otherwise use workoutdb (will auto create it)
      POSTGRES_USER: ${POSTGRES_USER:-workoutuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data #saving database outside the container so if it gets deleted the database stays
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql #when database gets created it runs to the init.sql file
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-workoutuser} -d ${POSTGRES_DB:-workoutdb}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - workout_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: workout_redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Redis uses port 6379
    networks:
      - workout_network # this makes sure that all services connect to the same docker network

  # celery
  celery:
    build: .
    container_name: workout_celery
    restart: unless-stopped
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - workout_network

  # Django
  web:
    build: .  # Uses docker file
    container_name: workout_django
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # if you edit code locally container updates immediately
    ports:
      - "8000:8000"
    environment:
      # Database connection
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-workoutdb}
      POSTGRES_USER: ${POSTGRES_USER:-workoutuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword123}

      # Django settings
      DJANGO_SETTINGS_MODULE: config.settings #settings directory
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-django-insecure-dev-key-change-me}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,postgres
    depends_on: # means don't start server unless postgres and redis are ready
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - workout_network

  # pgAdmin - Database Management
  pgadmin:
    image: dpage/pgadmin4
    container_name: workout_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@workoutapp.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - workout_network

# Define volumes
volumes:
  postgres_data:
    driver: local

# Define networks
networks:
  workout_network:
    driver: bridge