services:
  #WEB SERVICE FOR DJANGO API
  - type: web
    name: fittrack-api
    runtime: python
    repo : https://github.com/moaazrady92/fittrack-api
    plan : free
    region : oregon
    branch : master
    buildCommand: |
      pip install python requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn config.wsgi:application -bind 0.0.0.0:$PORT
    envVars:
      - key : DJANGO_SETTINGS_MODULE
        value : config.settings
      - key : DJANGO_SECRET_KEY
        generateValue: True
      - key : DJANGO_DEBUG
        value : False
      - key : POSTGRES_HOST
        fromDatabase:
          name : fittrack-db
          property: host
      - key : POSTGRES_USER
        fromDatabase:
          name : fittrack-db
          property: user
      - key : POSTGRES_PASSWORD
        fromDatabase:
          name : fittrack-db
          property: password
      - key : POSTGRES_DB
        fromDatabase:
          name : fittrack-db
          property: database


#PostgreSql Database
- type: postgresql
  name : fittrack-db
  plan : free
  region : oregon
  ipAllowList: []




